AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deepgram SE Demo - Full Stack

Parameters:
  DomainName:
    Type: String
    Default: deepgram.lesuto.com
  HostedZoneId:
    Type: String
    Default: Z021462718WHYPRPOOQ2 # Your specific Zone ID

Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref ConversationTable
        # We will fetch the key from Secrets Manager in the code, or env var
        # For simplicity in this demo, we assume you set this env var in the console 
        # OR better: use the Secrets Manager setup below.
        SECRETS_ARN: !Ref DeepgramSecret

Resources:
  # --- 1. STORAGE ---
  ConversationTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DeepgramDemo_Logs
      PrimaryKey:
        Name: session_id
        Type: String

  # --- 2. SECRETS (Placeholders) ---
  DeepgramSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DeepgramApiKey_Demo
      Description: API Key for Deepgram Demo
      SecretString: '{"api_key":"PLACEHOLDER_CHANGE_ME_IN_CONSOLE"}'

  # --- 3. BACKEND (LAMBDA) ---
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures: ["x86_64"]
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: 
            - !Sub "https://${DomainName}"
          AllowMethods: ["POST"]
          AllowHeaders: ["Content-Type"]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationTable
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref DeepgramSecret

  # --- 4. FRONTEND HOSTING (S3 + CloudFront + SSL) ---
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "deepgram-demo-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Policy to let CloudFront read S3
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistro}"

  # SSL Certificate
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  # CloudFront Distribution
  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: 
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.DomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  # --- 5. DNS ---
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront's Fixed Zone ID
        DNSName: !GetAtt CloudFrontDistro.DomainName

Outputs:
  ApiEndpoint:
    Description: "API URL for the Frontend"
    Value: !GetAtt BackendFunctionUrl.FunctionUrl
  BucketName:
    Value: !Ref FrontendBucket