AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deepgram SE Demo - Full Stack

Parameters:
  DomainName:
    Type: String
    Default: deepgram.lesuto.com
  HostedZoneId:
    Type: String
    Description: The Route53 Hosted Zone ID for lesuto.com

Globals:
  Function:
    Timeout: 15
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref ConversationTable
        DEEPGRAM_API_KEY: "{{resolve:secretsmanager:DeepgramApiKey}}" # Store key in AWS Secrets Manager manually first!

Resources:
  # 1. Database
  ConversationTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DeepgramDemo_Logs
      PrimaryKey:
        Name: session_id
        Type: String

  # 2. Backend API (Lambda)
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures: ["x86_64"]
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: 
            - !Sub "https://${DomainName}"
          AllowMethods: ["POST"]
          AllowHeaders: ["Content-Type"]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConversationTable
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"

  # 3. SSL Certificate (Auto-validated via DNS)
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  # 4. Frontend Hosting (S3)
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistro}"

  # 5. CDN (CloudFront)
  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: 
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.DomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  # 6. DNS Record
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # This is the fixed CloudFront Zone ID
        DNSName: !GetAtt CloudFrontDistro.DomainName

Outputs:
  ApiEndpoint:
    Value: !GetAtt BackendFunctionUrl.FunctionUrl
  BucketName:
    Value: !Ref FrontendBucket